Dev/dterletskiy/virtio integration
xen-troops/meta-xt-prod-devel-rcar pull request #100
Opened 2023-07-25 14:33 UTC by dterletskiy

2023-07-25 15:42 UTC, lorc requested changes
Could you please write comprehensive commit descriptions? 
Those are below any standards.

Also, @otyshchenko1, could you please take a look at the very first patch in this PR?

2023-07-25 15:42 UTC, lorc commented on meta-xt-prod-devel-rcar-driver-domain/recipes-kernel/linux/files/r8a77951-h3ulcb-domd.dts
AFAIK, H3ULCB is still supported. Why are you deleting its dts file?

2023-07-25 15:42 UTC, lorc commented on meta-xt-prod-devel-rcar-control/recipes-guests/domd/domd.bbappend
> +        echo "driver_domain = 1" >> ${CFG_FILE}
Is this a some new option for xl.cfg? Looks like it is temporary, as I don't believe, that any upstreamable xen tools code will have option like this

2023-07-25 15:42 UTC, lorc commented on meta-xt-prod-devel-rcar-control/recipes-guests/domu/domu.bbappend
> +python () {
Stray change?

2023-07-25 15:42 UTC, lorc commented on meta-xt-prod-devel-rcar-control/recipes-guests/domu/domu.bbappend
> +SRC_URI += " \
Do you need this change?

2023-07-25 15:42 UTC, lorc commented on meta-xt-prod-devel-rcar-control/recipes-guests/domu/domu.bbappend
> +    ${@bb.utils.contains('DISTRO_FEATURES', 'pvcamera', 'file://domu-pvcamera.cfg', '', d)} \
This has nothing to do with virtio

2023-07-26 09:45 UTC, dterletskiy commented on meta-xt-prod-devel-rcar-driver-domain/recipes-kernel/linux/files/r8a77951-h3ulcb-domd.dts
I believe we did it together and you with @otyshchenko1 confirmed this deletion.

2023-07-26 09:45 UTC, dterletskiy commented on meta-xt-prod-devel-rcar-control/recipes-guests/domu/domu.bbappend
> +python () {
Removed

2023-07-26 09:46 UTC, dterletskiy commented on meta-xt-prod-devel-rcar-control/recipes-guests/domu/domu.bbappend
> +SRC_URI += " \
Reverted

2023-07-26 09:46 UTC, dterletskiy commented on meta-xt-prod-devel-rcar-control/recipes-guests/domu/domu.bbappend
> +    ${@bb.utils.contains('DISTRO_FEATURES', 'pvcamera', 'file://domu-pvcamera.cfg', '', d)} \
Reverted

2023-07-26 10:21 UTC, dterletskiy commented
> Could you please write comprehensive commit descriptions? Those are below any standards.
> 
> Also, @otyshchenko1, could you please take a look at the very first patch in this PR?

Hi @lorc.
Done

2023-07-26 14:28 UTC, lorc commented on meta-xt-prod-devel-rcar-driver-domain/recipes-kernel/linux/files/r8a77951-h3ulcb-xen.dts
For some reason you mentioned only -domd.dts file in the commit message, but not this file. Is this a mistake?

2023-07-26 20:01 UTC, merged