Integration of QEMU v7.0.0 + switching to the Xen 4.18
xen-troops/meta-xt-prod-devel-rcar pull request #95
Opened 2023-07-04 22:21 UTC by svlad-90

xen & xen-tools: Switch to Xen 4.18
To use the virtio approach for sharing devices between the driver and the
guest Xen domains we need to switch to the Xen version 4.18. It contains
the required patches for the virtio use cases.

This patch switches to the usage of the xen-troops/xen of branch
xen-4.18-xt0.1, which is Xen of version 4.18 with additional xen-troops
patches on top of it, which were not yet upstreamed.

Signed-off-by: Vladyslav Goncharuk <vladyslav_goncharuk@epam.com>

----

yaml: Fix wrong moulin syntax in build config
For 'yes' literal of the 'ENABLE_ANDROID' parameter, for dom0, there was
a 'conf' section, which was declared outside of the 'builder'. That lead
to doma.cfg with an empty memory parameter, which blocked the start of
the Android OS.

This patch fixes the error in the configuration file.

Signed-off-by: Vladyslav Goncharuk <vladyslav_goncharuk@epam.com>

----

Browse the repository at this point in the history
yaml: Install qemu and friends into DomD
Now with having all required changes integrated into QEMU and
meta-xt-common we can set up an environment for DomD to get a proper
thin Xen-aware qemu-system-aarch64 with required dependencies.

At the same time, this patch adjusts an environment for Dom0 according
to the recent QEMU and meta-xt-common changes.

Signed-off-by: Vladyslav Goncharuk <vladyslav_goncharuk@epam.com>

2023-07-04 22:27 UTC, svlad-90 commented
Verification criteria:

https://github.com/xen-troops/meta-xt-prod-devel-rcar/pull/95/commits/3d6f2ab5b11c4d04a55ab7841ed0f50613adf82f - verified, that Android OS is started without ENABLE_VIRTIO on Kingfisher

https://github.com/xen-troops/meta-xt-prod-devel-rcar/pull/95/commits/ca3f92eceaece17d2522472314a2b5a34f5693de - verified version of Xen on the target:
```
xen_version            : 4.18-unstable
```

https://github.com/xen-troops/meta-xt-prod-devel-rcar/pull/95/commits/69d9a82ab11b870013fec345bd408fbe76108d58 - verified, that qemu-system-aarch64 is available in DomD, when built with ENABLE_VIRTIO. It understands the target '-xen-domid', '-xen-attach' parameters.

2023-07-06 01:22 UTC, lorc requested changes
There are lots of config entries that really should reside in the recipes/appends, because yocto-way is to use layers.

Also, imagine that you want to add virtio support  to another product. You will blow up its conf with the same entries, basically

2023-07-06 10:16 UTC, svlad-90 commented on prod-devel-rcar-agl.yaml
> +                - [QEMUVERSION, "7.0%"]
Hi @lorc, it is used inside poky to set the preferred QEMU version for build and installation:
https://github.com/yoctoproject/poky/blob/kirkstone/meta/conf/distro/include/tcmode-default.inc#L64

2023-07-07 09:30 UTC, svlad-90 commented on prod-devel-rcar.yaml
> +                - [PACKAGECONFIG:append:pn-libsdl2, " wayland gles2 arm-neon"]
Hi @lorc, all PACKAGECONFIG directives were:
- removed, if redundant
- moved to the bbappend of the corresponding package

Done.

2023-07-07 09:32 UTC, svlad-90 commented on prod-devel-rcar-agl.yaml
> +                - [QEMU_TARGETS, "aarch64"]
Hi @lorc,

Done. Was moved here - https://github.com/xen-troops/meta-xt-common/pull/56/files#diff-a8e21e523509863937d5e0924708c2055bf9c85f546c4d862b6a932cf2a2c5a6R3

2023-07-07 09:34 UTC, svlad-90 commented on prod-devel-rcar-agl.yaml
> +                - [PACKAGE_EXCLUDE:append, " qemu qemu-system-aarch64 qemu-keymaps qemu-support qemu-firmware"]
Hi @lorc, Done.

Actually, this line was not needed at all, thus I've removed it. But for other cases ( e.g. with domd ) IMAGE_INSTALL and PACKAGE_INSTALL were moved to the image's bbappend:
https://github.com/xen-troops/meta-xt-prod-devel-rcar/pull/95/files#diff-5f0339b7090f3004e65a3b7b4db33ee8b188b73364044aec95b84f3e4314b303R1

2023-07-07 13:33 UTC, lorc approved these changes
`Acked-by: Volodymyr Babchuk <volodymyr_babchuk@epam.com>`

2023-07-07 13:41 UTC, merged